# 下载环境对应的包
# 配置对应的源
FROM rust:1.31
FROM enmotech/opengauss:2.1.0
FROM node:14.19.1
RUN npm i --registry=https://registry.npm.taobao.org

RUN mkdir -p /app/mail2list/backend
COPY mail2list_backend/mail2list_web app/mail2list/backend/mail2list_web


EXPOSE 9999

RUN cargo install --path /app/mail2list/backend/mail2list_web
CMD ["mail2list_web"]
