[package]
name = "rpmust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
thiserror = "1"
num-derive = "0.3"
num-traits = "0.2"
enum-primitive-derive = "0.2"
enum-display-derive = "0.1"