FROM node:14.19.1 as builder
WORKDIR /app
COPY package.json .
RUN npm install --unsafe-perma --registry=http://registry.npm.taobao.org
COPY . .
RUN npm run build

FROM nginx:latest
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 8081