[package]
name = "dagrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.5"
lazy_static = "1.4.0"
bimap = "0.6.1"
clap = { version = "3.0.14", features = ["derive"] }